name:                Mangekyou-Sharingan
version:             0.1.0.0
github:              "terrynini/Mangekyou-Sharingan"
author:              "terrynini"
maintainer:          "terrynini38514@gmail.com"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/terrynini/Mangekyou-Sharingan#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- llvm-hs
- integer-gmp
- haskeline
- mtl

library:
  source-dirs: src

executables:
  Mangekyou-Sharingan-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Mangekyou-Sharingan

tests:
  Mangekyou-Sharingan-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Mangekyou-Sharingan
